#!/usr/bin/env python3
"""
GitOps Documentation Pipeline - Example Usage
Demonstrates GitOps integration for Documentation-as-Code workflows.
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))


def example_git_operations():
    """Example: Basic Git operations."""
    print("=" * 60)
    print("GitOps Example 1: Basic Git Operations")
    print("=" * 60)
    
    from src.gitops.git_manager import GitManager, GitConfig
    
    # Create temporary directory for demo
    demo_dir = Path("data/gitops_demo")
    demo_dir.mkdir(parents=True, exist_ok=True)
    
    # Initialize Git Manager
    config = GitConfig(
        repo_path=demo_dir,
        author_name="AHG Demo",
        author_email="demo@example.com",
        branch="main"
    )
    
    manager = GitManager(config)
    print(f"✅ Git Repository initialisiert: {demo_dir}")
    
    # Create a sample documentation file
    doc_file = demo_dir / "docs" / "example.md"
    doc_file.parent.mkdir(parents=True, exist_ok=True)
    doc_file.write_text("""
# Example Documentation

This is an example documentation file generated by AHG.

## Steps

1. First step
2. Second step
3. Third step
""", encoding='utf-8')
    
    print(f"✅ Dokumentationsdatei erstellt: {doc_file}")
    
    # Stage and commit
    manager.add(["docs/example.md"])
    commit_hash = manager.commit("docs: Add example documentation")
    
    print(f"✅ Committed: {commit_hash[:8]}")
    
    # Get status
    status = manager.status()
    print(f"\n📊 Repository Status:")
    print(f"   Branch: {status['current_branch']}")
    print(f"   Last Commit: {status['last_commit']}")
    print(f"   Untracked: {len(status['untracked_files'])}")
    
    return manager


def example_ai_commits():
    """Example: AI-generated commit messages."""
    print("\n" + "=" * 60)
    print("GitOps Example 2: AI-Generated Commit Messages")
    print("=" * 60)
    
    from src.gitops.commit_generator import CommitGenerator, CommitContext
    
    generator = CommitGenerator(language="de")
    
    context = CommitContext(
        files_changed=["docs/manual.md", "docs/tutorial.md"],
        diff_summary="Added user registration workflow with 5 steps",
        session_title="Benutzer-Registrierung",
        step_count=5,
        documentation_type="manual"
    )
    
    if generator.client:
        message = generator.generate_commit_message(context, style="conventional")
        print(f"✅ AI-generierte Commit-Message:")
        print(f"   {message}")
    else:
        message = generator._generate_basic_message(context)
        print(f"⚠️  Basic Commit-Message (OpenAI nicht verfügbar):")
        print(f"   {message}")


def example_repository_sync():
    """Example: Repository synchronization."""
    print("\n" + "=" * 60)
    print("GitOps Example 3: Repository Synchronization")
    print("=" * 60)
    
    from src.gitops.git_manager import GitManager, GitConfig
    from src.gitops.repository_sync import RepositorySync, SyncConfig
    
    demo_dir = Path("data/gitops_demo")
    
    git_config = GitConfig(repo_path=demo_dir)
    git_manager = GitManager(git_config)
    
    sync_config = SyncConfig(
        auto_sync=True,
        sync_interval=300,
        conflict_strategy="merge",
        sync_on_session_end=True,
        sync_on_export=True
    )
    
    sync = RepositorySync(git_manager, sync_config)
    
    # Create a new file
    new_file = demo_dir / "docs" / "update.md"
    new_file.write_text("# Updated Documentation\n\nNew content.", encoding='utf-8')
    
    # Sync to Git
    result = sync.sync_to_git(
        files=["docs/update.md"],
        commit_message="docs: Add update documentation"
    )
    
    if result:
        print("✅ Dateien erfolgreich zu Git synchronisiert")
    
    # Get sync status
    status = sync.get_sync_status()
    print(f"\n📊 Sync Status:")
    print(f"   Last Sync: {status.get('last_sync', 'Nie')}")
    print(f"   Pending Changes: {status.get('pending_changes', 0)}")
    print(f"   Current Branch: {status.get('current_branch', 'N/A')}")


def example_pr_automation():
    """Example: Pull Request automation."""
    print("\n" + "=" * 60)
    print("GitOps Example 4: Pull Request Automation")
    print("=" * 60)
    
    from src.gitops.pr_automation import PRAutomation, PRConfig, Platform
    
    # Check for tokens
    github_token = os.getenv("GITHUB_TOKEN")
    gitlab_token = os.getenv("GITLAB_TOKEN")
    
    if not github_token and not gitlab_token:
        print("⚠️  GITHUB_TOKEN oder GITLAB_TOKEN nicht gesetzt")
        print("   PR-Automation erfordert Authentifizierung")
        return
    
    platform = Platform.GITHUB if github_token else Platform.GITLAB
    repo = "owner/repo"  # Would be configured in real scenario
    
    config = PRConfig(
        platform=platform,
        repository=repo,
        base_branch="main",
        labels=["documentation", "automated"]
    )
    
    automation = PRAutomation(config)
    
    if automation.client:
        print(f"✅ {platform.value.upper()} Client initialisiert")
        print(f"   Repository: {repo}")
        print(f"   Base Branch: {config.base_branch}")
        print("\n💡 In Produktion würde hier ein PR erstellt werden:")
        print("   automation.create_pr('feature/docs-update', 'docs: Update', 'Description')")
    else:
        print("⚠️  PR-Client nicht initialisiert (Token fehlt)")


def main():
    """Run all examples."""
    print("\n🚀 GitOps Documentation Pipeline - Examples\n")
    
    try:
        # Example 1: Basic Git operations
        manager = example_git_operations()
        
        # Example 2: AI commits
        example_ai_commits()
        
        # Example 3: Repository sync
        example_repository_sync()
        
        # Example 4: PR automation
        example_pr_automation()
        
        print("\n" + "=" * 60)
        print("✅ Alle Beispiele erfolgreich ausgeführt!")
        print("=" * 60)
        print("\n📁 Demo-Repository erstellt in: data/gitops_demo/")
        print("💡 Sie können das Repository mit Git-Befehlen weiter verwenden")
        
    except Exception as e:
        print(f"\n❌ Fehler: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0


if __name__ == "__main__":
    sys.exit(main())

